### PR TITLE
feat: adds the prettier plugin for tailwindcss if prettier is used

### PR DESCRIPTION
**Pull request by delight**
The plugin puts the used tailwindcss utility classes in order

Since a skeleton project is using tailwindcss, we should add the prettier plugin for tailwindcss if prettier is selected. 

Improves DX

### CODE REVIEW

**Comment by endigo9740** [comment]
@delight @niktek Just because we can, doesn't mean we should in every respect. The goal with the CLI is a lightweight experience that lets folks easily scaffold a SvelteKit app with Skeleton preconfigured. We're not trying to build and maintain everyone's stack here. It's not our place and not our responsibility.

The more complexity we add to this, the less responsive some folks are going to be to it. Plus the more maintenance we have to keep up with. So need to be very careful that we're picking our battles wisely here.

And before you ask - just adding another prompt or option isn't really an adequate solution. Because again, the complexity ceiling raises every single time we do that.

I'll leave it up to you guys to decide if this is worthwhile or not, but please spend some time considering what's worth the effort and the maintenance cost to our team. Our focus should be simplicity, plain and simple. We don't want this to grow into an unruly monster.

**Comment by delight** [comment]
@endigo9740 I agree in general. But for this particular case it is no prompt or any complexity included and as you can see by the PR it is maintenance-free.

- no additional complexity
> - no prompt
> - no config

It is just added alongside if you select prettier for your project and it works behind the scenes when you apply prettier to your code.
In the end it is simply an additional dev-dependency, which as mentioned is paired with prettier itself.

This plugin helps keeping your tailwind css classes tidy and in an opinionated order and therefor helps in clarity. It is simply logical to use when you work with tailwindcss.

I don't see how it makes it heavy and for sure it does not raise the complexity - but it enhances the dx, which is the aim of that PR. In the end this should be one of the ultimate goal for any framework IMO.

fyi:  [Sorting Tailwind CSS Classes Automatically with Prettier ](https://www.youtube.com/watch?v=_CntOc4hBcg)

**Comment by delight** [comment]
In the end it is similar to the use of prettier-plugin-svelte as we are in a svelte project - even though arguably the benefit or the svelte plugin is even higher. But as skeleton projects are tailwind bases we should provide also the best setup for the developers. 

> We're not trying to build and maintain everyone's stack here.

I haven't set up a new project since, but I felt that some things are general beneficial and therefore I proposed those ideas and changes so that ppl can benefit of it when they use the cli - resulting in a better experience. 
Just wanted to make clear that by any means I don't try to cover my own use case here.

**Comment by endigo9740** [comment]
It doesn't matter what the plugin does, or the use case, the issue is it is installing an unprompted dependency (dev or otherwise) without the user's consent. Especially this one, given it's an opinionated optional plugin that has a direct impact on folk's code.

What if someone doesn't want this feature? That they have no idea it's being forced on them? What if they don't realize this is the feature making unwanted changes in their project? Then they have to spend time debugging, locate it, and remove it. Who do you think they're going to be upset with after that process - the plugin maker or us? (hint: it's us)

When building for other people, you can't the stance of "I know better than everyone else" and strong arm stuff you want to use in your own projects. You have to take the stance that in most cases most people want simplicity, then to build up from that as they see fit. It's not for us to decide what that process looks like.

> But for this particular case it is no prompt or any complexity included and as you can see by the PR it is maintenance-free.

> I don't see how it makes it heavy and for sure it does not raise the complexity

Every dependency is a point of failure. Everything we introduce has a maintenance cost. When a breaking issue is introduced in ANY dependency then our users are affected. And folks like myself, Nik, and Dom have to devote our time to providing support to those affected users. So no, I wouldn't call this "maintenance-free" or without complexity.

Just because it's easy to add, doesn't mean it's easy to support and will never break.

**Comment by delight** [comment]
I just thought it is similar to how the prettier-plugin-svelte dependency is added in the background for the svelte functionality it is the same for tailwindcss. 

So maybe I was wrong on proposing my idea for improving the experience. 

So then just close simply the PR - I meant well but didn't think it would be such a big burden.

**Comment by niktek** [comment]
So I've been holding off on this one till I get a better feel for what's really involved.

1) The maintenance on the CLI hasn't been that bad, the only real updates required have come from Skeleton itself - which is to be expected.
2) Prettier itself is opinionated (for good reason and quite literally its reason for existence) and this just extends that choice that the user has already made.
3) This plugin is totally useless for Skeleton itself (dynamic string constructions etc), but considering the actual users of Skeleton, considering that they will be newer to TW, that it will make their own code easier to read and considering that this is the recommended way to do TW classes by the TW [website](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted) and Adam and Simon contributed to the plugin and it's used by 54k other devs - I don't see any reason to not add it.

Having said that - I'm not going to accept this PR because it currently doesn't properly setup the plugin.

.prettierrc needs to be updated with the plugin in it's listing and it MUST be the last plugin
auto plugin loading needs to be disabled in .prettierrc
auto plugin loading needs to be disabled in the 'format' command

[Info](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins)

**Comment by delight** [comment]
> So I've been holding off on this one till I get a better feel for what's really involved.
> 
>     1. The maintenance on the CLI hasn't been that bad, the only real updates required have come from Skeleton itself - which is to be expected.
> 
>     2. Prettier itself is opinionated (for good reason and quite literally its reason for existence) and this just extends that choice that the user has already made.
> 
>     3. This plugin is totally useless for Skeleton itself (dynamic string constructions etc), but considering the actual users of Skeleton, considering that they will be newer to TW, that it will make their own code easier to read and considering that this is the recommended way to do TW classes by the TW [website](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted) and Adam and Simon contributed to the plugin and it's used by 54k other devs - I don't see any reason to not add it.
> 
> 
> Having said that - I'm not going to accept this PR because it currently doesn't properly setup the plugin.
> 
> .prettierrc needs to be updated with the plugin in it's listing and it MUST be the last plugin auto plugin loading needs to be disabled in .prettierrc auto plugin loading needs to be disabled in the 'format' command
> 
> [Info](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins)

Interesting, I didn't even know about it up till know. For me `pnpm i -D prettier-plugin-tailwindcss` is all it took/takes to make it work, even though it states: 

> _"Note that plugin autoloading is not supported when using certain package managers, such as pnpm or Yarn PnP. In this case you may need to add the plugin to your Prettier config explicitly:"_

Nevertheless, it is all good 👍 -> Developers can do that simple step themselves when they want to use the plugin (and resolve any potential conflicts they have if it is not working). Should not be in the hands of the cli as Chris mentioned initially.

**Pull request closed without merging**
